/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as Example2IndexImport } from './routes/example2/index'
import { Route as Example1IndexImport } from './routes/example1/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Example2IndexRoute = Example2IndexImport.update({
  id: '/example2/',
  path: '/example2/',
  getParentRoute: () => rootRoute,
} as any)

const Example1IndexRoute = Example1IndexImport.update({
  id: '/example1/',
  path: '/example1/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/example1/': {
      id: '/example1/'
      path: '/example1'
      fullPath: '/example1'
      preLoaderRoute: typeof Example1IndexImport
      parentRoute: typeof rootRoute
    }
    '/example2/': {
      id: '/example2/'
      path: '/example2'
      fullPath: '/example2'
      preLoaderRoute: typeof Example2IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example1': typeof Example1IndexRoute
  '/example2': typeof Example2IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example1': typeof Example1IndexRoute
  '/example2': typeof Example2IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/example1/': typeof Example1IndexRoute
  '/example2/': typeof Example2IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/example1' | '/example2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example1' | '/example2'
  id: '__root__' | '/' | '/example1/' | '/example2/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Example1IndexRoute: typeof Example1IndexRoute
  Example2IndexRoute: typeof Example2IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Example1IndexRoute: Example1IndexRoute,
  Example2IndexRoute: Example2IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/example1/",
        "/example2/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/example1/": {
      "filePath": "example1/index.tsx"
    },
    "/example2/": {
      "filePath": "example2/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
